import { readFileSync } from "node:fs";
const s = readFileSync("c:/Users/Windows11/Documents/GitHub/crm/zuarts-conecta-gestao/prisma/migrations/20260910180000_etapa07_modulos_capacidades/migration.sql", "utf8");
const head = s.indexOf('INSERT INTO "Capability"');
const tail = s.indexOf('INSERT INTO "PlanModule"');
const block = s.slice(head, tail);
console.log("head:", head, "tail:", tail);
console.log("--- block first 6 lines ---");
console.log(block.split("\n").slice(0, 6).join("\n"));
console.log("--- row endings sample ---");
const rows = block.split("\n").filter((l) => l.startsWith("('9c7d"));
console.log("row count:", rows.length);
console.log(JSON.stringify(rows[0]));
console.log(JSON.stringify(rows[rows.length - 1]));